name: sns_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: any
  image_picker: ^0.8.5
  firebase_core: ^1.18.0
  firebase_auth: ^3.3.20
  firebase_storage: ^10.2.18

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
